; PlatformIO Project Configuration File
; Automated conversion for TTS_ESP32

[platformio]
src_dir = .
default_envs = TTS_ESP32

[env]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
    Wire
    SPI

[env:TTS_ESP32]
build_src_filter = +<TTS_ESP32/> -<*>
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    earlephilhower/ESP8266SAM
